apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "locust-secret"
    nginx.ingress.kubernetes.io/auth-realm: "Autenticao necessaria"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - locust.carlosclaro.com.br
    secretName: locust-carlosclaro-tls-prod
  rules:
  - host: locust.carlosclaro.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: locust-giropops
            port:
              number: 80